POST http://127.0.0.1:3000/api/auth/registro
Content-Type: application/json

{
    "nombre": "Ana",
    "apellidos": "Pruebas",
    "email": "ana@gmail.com",
    "password": "ana54321"
}

### LOGIN
POST http://127.0.0.1:3000/api/auth/login
Content-Type: application/json

{
    "email": "ana@gmail.com",
    "password": "ana54321"
}

### PERFIL
GET http://127.0.0.1:3000/api/auth/perfil
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiZW1haWwiOiJhbmFAZ21haWwuY29tIiwidGltZSI6IjIwMjItMTItMjJUMDE6NDg6MDEuNDI0WiIsImlhdCI6MTY3MTY3MzY4MSwiZXhwIjoxNjcxNjc3MjgxfQ.w3EDSBGZUbuJCZ-cUB1czYkmmLzqvjsBPgJQutmKqkg
